<?php
use MapasCulturais\i;

return array(
    1 => array(
        'slug' => 'tag',
        'description' => i::__('Tag'),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Event',
            'MapasCulturais\Entities\Project',
            'MapasCulturais\Entities\Opportunity',
        )
    ),

    2 => array(
        'slug' => 'area',
        'description' => i::__('Área de Atuação'),
        'required' => i::__("Você deve informar ao menos uma área de atuação"),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Opportunity',
        ),
        'restricted_terms' => array(
                i::__("Agroextrativismo"),
                i::__("Artesanato"),
                i::__("Ecoturismo"),
                i::__("Caça"),
                i::__("Pesca"),
                i::__("Roçado"),
                i::__("Agricultura Familiar"),
                i::__("Apicultura"),
                i::__("Açaicultura"),
                i::__("Castanha"),
                i::__("Babaçu"),
                i::__("Borracha"),
                i::__("Óleos Vegetais"),
                i::__("Sementes Tradicionais"),
                i::__("Gastronomia / Alimentação"),
                i::__("Medicina Tradicional"),
                i::__("Saúde Comunitária"),
                i::__("Educação"),
                i::__("Educação Popular"),
                i::__("Cultura"),
                i::__("Esporte"),
                i::__("Religiosidade"),
                i::__("Espiritualidade"),
                i::__("Cuidado"),
                i::__("Trabalho Doméstico"),
                i::__("Construção Civil"),
                i::__("Carpintaria / Marcenaria"),
                i::__("Transporte"),
                i::__("Navegação"),
                i::__("Comunicação Popular"),
                i::__("Cultura Digital"),
                i::__("Gestão Ambiental"),
                i::__("Conservação da Floresta"),
                i::__("Sustentabilidade"),
                i::__("Turismo de Base Comunitária"),
                i::__("Comércio Local"),
                i::__("Feiras e Mercados"),
                i::__("Economia Solidária"),
                i::__("Costura"),
                i::__("Moda Sustentável"),
                i::__("Reciclagem / Reaproveitamento"),
                i::__("Energia Renovável"),
                i::__("Governança Territorial"),
                i::__("Articulação Comunitária"),
                i::__("Participação Social"),
                i::__("Gestão de Projetos"),
                i::__("Defesa de Direitos"),
                i::__("Juventude"),
                i::__("Mulheres"),
                i::__("Infância"),
                i::__("Povos Originários"),
                i::__("Povos da Floresta"),
                i::__("Visitante"),
                i::__("Apoiadora"),
                i::__("Outros"),
        )
    ),

    3 => array(
        'slug' => 'linguagem',
        'description' => i::__('Linguagem'),
        'required' => i::__("Você deve informar ao menos uma linguagem"),
        'entities' => array(
            'MapasCulturais\Entities\Event'
        ),

        'restricted_terms' => array(
            i::__('Soberania Digital Popular'),
            i::__('Soberania Alimentar'),
            i::__('Povos da Floresta'),
            i::__('Povos Originários'),
            i::__('Diversidade (LGBTQIAPN+)'),
            i::__('Feminista'),
            i::__('Infância'),
            i::__('Juventude'),
            i::__('Cultura'),
            i::__('Cultura Digital'),
            i::__('Inclusão Digital'),
            i::__('Acesso a Direitos'),
            i::__('Justiça Social'),
            i::__('Justiça Climática'),
            i::__('Governança Territorial'),
            i::__('Direitos da Terra'),
            i::__('Democracia'),
            i::__('Economia Solidária'),
            i::__('Educação Popular'),
            i::__('Agroecologia'),
            i::__('Comunicação Popular'),
            i::__('Audiovisual'),
            i::__('Cinema'),
            i::__('Fotografia'),
            i::__('Rádio Comunitária'),
            i::__('Podcast'),
            i::__('Artes Cênicas'),
            i::__('eatro'),
            i::__('Artes Circenses'),
            i::__('Música'),
            i::__('Dança'),
            i::__('Literatura'),
            i::__('Poesia Falada / Slam'),
            i::__('Design'),
            i::__('Artesanato'),
            i::__('Moda Sustentável'),
            i::__('Gastronomia Tradicional'),
            i::__('Saberes da Floresta'),
            i::__('Saberes Ancestrais'),
            i::__('Memória e Patrimônio'),
            i::__('Espiritualidade e Cura'),
            i::__('Tecnologia Social'),
            i::__('Ciência Cidadã'),
            i::__('Inovação Comunitária'),
            i::__('Territórios Livres'),
            i::__('Movimentos Sociais'),
            i::__('Outros')
        ),
    ),

   
    4 => array(
        'slug' => 'funcao',
        'description' => i::__('Função'),
        'entities' => array(
            'MapasCulturais\Entities\Agent'
        ),
        'restricted_terms' => array(
           i::__('Agente Ambiental'),
           i::__('Agente Comunitário(a)'),
           i::__('Agente Cultural'),
           i::__('Agente de Saúde'),
           i::__('Agente Pastoral'),
           i::__('Agricultor(a)'),
           i::__('Agroextrativista'),
           i::__('Analista de Dados'),
           i::__('Apicultor(a)'),
           i::__('Apresentador(a)'),
           i::__('Apoiador(a)'),
           i::__('Apoiador(a) Técnico(a)'),
           i::__('Artesão(ã)'),
           i::__('Articulador(a)'),
           i::__('Articulador(a) de Rede'),
           i::__('Artista'),
           i::__('Ator / Atriz'),
           i::__('Benzedeira'),
           i::__('Barqueiro(a)'),
           i::__('Brigadista'),
           i::__('Caçador(a)'),
           i::__('Cantor(a)'),
           i::__('Carpinteiro(a)'),
           i::__('Catequista'),
           i::__('Ceramista'),
           i::__('Circense'),
           i::__('Comerciante'),
           i::__('Compositor(a)'),
           i::__('Comunicador(a) Popular'),
           i::__('Condutor(a) de Turistas'),
           i::__('Construtor(a) de Embarcações'),
           i::__('Coordenador(a)'),
           i::__('Cozinheira Comunitária'),
           i::__('Cozinheiro(a)'),
           i::__('Cuidador(a)'),
           i::__('Cuidador(a) de Idosos'),
           i::__('Curandeiro(a)'),
           i::__('Dançarino(a)'),
           i::__('Defesa de Direitos'),
           i::__('Desenvolvedor(a)'),
           i::__('Designer'),
           i::__('DJ'),
           i::__('Educador(a)'),
           i::__('Educador(a) Infantil'),
           i::__('Editor(a) de Vídeo'),
           i::__('Enfermeiro(a)'),
           i::__('Erveiro(a)'),
           i::__('Escritor(a)'),
           i::__('Esportista'),
           i::__('Estudante'),
           i::__('Facilitador(a)'),
           i::__('Facilitador(a) Territorial'),
           i::__('Feirante'),
           i::__('Fotógrafo(a)'),
           i::__('Fotógrafo(a) Comunitário(a)'),
           i::__('Gestor(a) Ambiental'),
           i::__('Gestor(a) de Projeto'),
           i::__('Guia Comunitário(a)'),
           i::__('Guia de Trilha'),
           i::__('Guia Espiritual'),
           i::__('Ilustrador(a)'),
           i::__('Instrutor(a) de Esporte'),
           i::__('Jornalista'),
           i::__('Juventude Comunitária'),
           i::__('Liderança Comunitária'),
           i::__('Liderança Religiosa'),
           i::__('Marceneiro(a)'),
           i::__('Mediador(a)'),
           i::__('Missionário(a)'),
           i::__('Mobilizador(a)'),
           i::__('Motorista'),
           i::__('Mestre de Obras'),
           i::__('Mulher de Rede'),
           i::__('Músico(a)'),
           i::__('Operador(a) de Rádio'),
           i::__('Outros'),
           i::__('Pajé'),
           i::__('Palhaço(a)'),
           i::__('Parteira'),
           i::__('Parteira Espiritual'),
           i::__('Parteira Tradicional'),
           i::__('Pedreiro(a)'),
           i::__('Pesquisador(a)'),
           i::__('Pescador(a)'),
           i::__('Poeta / Slamer'),
           i::__('Presidente de Associação'),
           i::__('Produtor(a) Audiovisual'),
           i::__('Produtor(a) Cultural'),
           i::__('Produtor(a) Rural'),
           i::__('Programador(a)'),
           i::__('Radialista'),
           i::__('Raizeiro(a)'),
           i::__('Representante de Associação'),
           i::__('Rezador(a)'),
           i::__('Roteirista'),
           i::__('Secretário(a)'),
           i::__('Seringueiro(a)'),
           i::__('Tecelão(ã)'),
           i::__('Técnico(a) Ambiental'),
           i::__('Técnico(a) de Enfermagem'),
           i::__('Técnico(a) de Informática'),
           i::__('Tesoureiro(a)'),
           i::__('Trabalhador(a) Doméstico(a)'),
           i::__('Treinador(a)'),
           i::__('Trançador(a)'),
           i::__('Voluntário(a)'),
           i::__('Visitante'),
           i::__('Xamã'),
        )
    )
);
