<?php
use MapasCulturais\i;

return array(
    1 => array(
        'slug' => 'tag',
        'description' => i::__('Tag'),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Event',
            'MapasCulturais\Entities\Project',
            'MapasCulturais\Entities\Opportunity',
        )
    ),

    2 => array(
        'slug' => 'area',
        'description' => i::__('Área de Atuação'),
        'required' => i::__("Você deve informar ao menos uma área de atuação"),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Opportunity',
        ),
        'restricted_terms' => array(
            i::__('Acervos'),
            i::__('Acessibilidade Cultural'),
            i::__('Agrofloresta'),
            i::__('Animação'),
            i::__('Açaicultura'),
            i::__('Áreas Técnicas'),
            i::__('Ecoturismo'),
            i::__('Caça'),
            i::__('Pesca'),
            i::__('Arte de Plásticas'),
            i::__('Roçado'),
            i::__('Agricultura Familiar'),
            i::__('Arte Gráfica'),
            i::__('Arte Santeira'),
            i::__('Agroextrativismo'),
            i::__('Apicultura'),
            i::__('Artesanato'),
            i::__('Artesanato com Reciclados'),
            i::__('Artesanato em Cerâmica'),
            i::__('Artesanato em Fibra Vegetal'),
            i::__('Artesanato em Fio'),
            i::__('Artesanato em Madeira'),
            i::__('Artesanato em Metal'),
            i::__('Artesanato em Pedra'),
            i::__('Artesanato em Tecido'),
            i::__('Audiolivro'),
            i::__('Audiovisual e Mídias Interativas'),
            i::__('Audiovisual Expandido'),
            i::__('Axé'),
            i::__('Baião'),
            i::__('Baião (dança)'),
            i::__('Ballet'),
            i::__('Banda'),
            i::__('Banda Sinfônica'),
            i::__('Bandas de Congo e Ticumbi'),
            i::__('Biblioteca'),
            i::__('Biblioteca tombada'),
            i::__('Biblioteconomia'),
            i::__('Bioconstrução'),
            i::__('Biografia e Autobiografia'),
            i::__('Bloco de Carnaval'),
            i::__('Boi Bumbá'),
            i::__('Bordado'),
            i::__('Breakdance'),
            i::__('Brega Funk'),
            i::__('Caboclinho'),
            i::__('Caçada da Rainha'),
            i::__('Calypso'),
            i::__('Canto'),
            i::__('Canto Coral'),
            i::__('Capoeira'),
            i::__('Carimbó'),
            i::__('Carimbó (Dança)'),
            i::__('Carnaval'),
            i::__('Cavalhadas'),
            i::__('Cavalo Marinho'),
            i::__('Centro de Memória e patrimônio'),
            i::__('Ciência Política'),
            i::__('Babaçu'),
            i::__('Cinemateca'),
            i::__('Ciranda'),
            i::__('Borracha'),
            i::__('Circo Contemporâneo'),
            i::__('Circo de Rua'),
            i::__('Circo Itinerante'),
            i::__('Circo Tradicional'),
            i::__('Coco'),
            i::__('Comédia'),
            i::__('Óleos Vegetais'),
            i::__('Congada'),
            i::__('Congado'),
            i::__('Contação de histórias'),
            i::__('Conteúdo Audiovisual por Demanda'),
            i::__('Conto'),
            i::__('Cordel'),
            i::__('Criação literária'),
            i::__('Crochê'),
            i::__('Crônica'),
            i::__('Cultivo e extração tradicional'),
            i::__('Cultura Alemã'),
            i::__('Cultura Alimentar'),
            i::__('Sementes Tradicionais'),
            i::__('Cultura da juventude de povos e comunidades tradicionais'),
            i::__('Cultura das comunidades de fundo e fecho de pasto'),
            i::__('Cultura das comunidades quilombolas'),
            i::__('Cultura das quebradeiras de coco babaçu'),
            i::__('Cultura DEF'),
            i::__('Gastronomia / Alimentação'),
            i::__('Cultura do Povo Arara'),
            i::__('Cultura do Povo Araweté'),
            i::__('Cultura do Povo Ashaninka'),
            i::__('Cultura do Povo Bororo'),
            i::__('Cultura do Povo Cultura Fulni-ô'),
            i::__('Cultura do Povo Enawenê-Nawê'),
            i::__('Cultura do Povo Gavião'),
            i::__('Cultura do Povo Guarani'),
            i::__('Cultura do Povo Ikpeng'),
            i::__('Cultura do Povo Javari'),
            i::__('Cultura do Povo Kalapalo'),
            i::__('Cultura do Povo Kanamari'),
            i::__('Cultura do Povo Karajá'),
            i::__('Cultura do Povo Karipuna'),
            i::__('Cultura do Povo Kaxinawá (Huni Kuin)'),
            i::__('Cultura do Povo Kayabi'),
            i::__('Cultura do Povo Kayapó'),
            i::__('Cultura do Povo Korubo'),
            i::__('Cultura do Povo Krahô'),
            i::__('Cultura do Povo Maxakali'),
            i::__('Cultura do Povo Munduruku'),
            i::__('Cultura do Povo Ofaié'),
            i::__('Cultura do Povo Panará'),
            i::__('Cultura do Povo Pankararu'),
            i::__('Cultura do Povo Pareci'),
            i::__('Cultura do Povo Paresí'),
            i::__('Cultura do Povo Pataxó'),
            i::__('Cultura do povo pomerano'),
            i::__('Cultura do Povo Suruí'),
            i::__('Cultura do Povo Tembé'),
            i::__('Cultura do Povo Terena'),
            i::__('Cultura do Povo Tikuna'),
            i::__('Cultura do Povo Timbira'),
            i::__('Cultura do Povo Tukano'),
            i::__('Cultura do Povo Tupi'),
            i::__('Cultura do Povo Wai Wai'),
            i::__('Cultura do Povo Waimiri-Atroari'),
            i::__('Cultura do Povo Xavante'),
            i::__('Cultura do Povo Xerente'),
            i::__('Cultura do Povo Xikrin'),
            i::__('Cultura do Povo Yanomami'),
            i::__('Cultura do Povo Yawalapiti'),
            i::__('Cultura do Povo Yawanawá'),
            i::__('Cultura do Povo Zoró'),
            i::__('Cultura dos andirobeiros'),
            i::__('Cultura dos apanhadores de flores sempre vivas'),
            i::__('Cultura dos benzedeiros'),
            i::__('Cultura dos caatingueiros'),
            i::__('Cultura dos caboclos'),
            i::__('Cultura dos caiçaras'),
            i::__('Cultura dos catadores de mangaba'),
            i::__('Cultura dos cipozeiros'),
            i::__('Cultura dos extrativistas'),
            i::__('Cultura dos extrativistas costeiros e marinhos'),
            i::__('Cultura dos faxinalenses'),
            i::__('Cultura dos geraizeiros'),
            i::__('Cultura dos ilhéus'),
            i::__('Cultura dos morroquianos'),
            i::__('Cultura dos pantaneiros'),
            i::__('Cultura dos pescadores artesanais'),
            i::__('Cultura dos povos ciganos'),
            i::__('Cultura dos povos e comunidades de terreiro/povos e comunidades de matriz africana'),
            i::__('Cultura dos Povos Nômades'),
            i::__('Cultura dos Povos Originários'),
            i::__('Cultura dos raizeiros'),
            i::__('Cultura dos retireiros do Araguaia'),
            i::__('Cultura dos ribeirinhos'),
            i::__('Cultura dos vazanteiros'),
            i::__('Cultura dos veredeiros'),
            i::__('Cultura e Bem Viver'),
            i::__('Cultura e Comunicação'),
            i::__('Cultura e decolonialidade'),
            i::__('Cultura e Desenvolvimento Social'),
            i::__('Cultura e Direitos Humanos'),
            i::__('Cultura e Educação'),
            i::__('Cultura e Esporte'),
            i::__('Cultura e Juventudes'),
            i::__('Cultura e Lazer'),
            i::__('Cultura e Política'),
            i::__('Cultura e Saúde'),
            i::__('Cultura e Território'),
            i::__('Cultura e Turismo'),
            i::__('Medicina Tradicional'),
            i::__('Cultura Hip Hop'),
            i::__('Cultura Italiana'),
            i::__('Cultura Japonesa'),
            i::__('Cultura LGBTQIAPN+'),
            i::__('Educação Popular'),
            i::__('Cultura Urbana'),
            i::__('Cultura, Infância e Adolescência'),
            i::__('Cultura, Meio Ambiente e Sustentabilidade'),
            i::__('Culturas Afrobrasileiras'),
            i::__('Culturas dos Povos Originários'),
            i::__('Culturas Populares'),
            i::__('Culturas Tradicionais'),
            i::__('Culturas Tradicionais e Populares'),
            i::__('Construção Civil'),
            i::__('Dança Afro'),
            i::__('Dança Contemporânea'),
            i::__('Dança de Salão'),
            i::__('Dança do Ventre'),
            i::__('Dança Moderna'),
            i::__('Dança Silvestre'),
            i::__('Danças Clássicas'),
            i::__('Danças Contemporâneas'),
            i::__('Danças Estrangeiras'),
            i::__('Danças Populares'),
            i::__('Danças Urbanas'),
            i::__('Declamação'),
            i::__('Desenho Industrial'),
            i::__('Religiosidade'),
            i::__('Design de Interiores'),
            i::__('Design de Jóias'),
            i::__('Design de Moda'),
            i::__('Design e Serviços Criativos'),
            i::__('Design Gráfico'),
            i::__('Design Paisagístico'),
            i::__('Design para a Sociobioeconomia'),
            i::__('Diário'),
            i::__('Direito'),
            i::__('Espiritualidade'),
            i::__('Documentário'),
            i::__('Drama'),
            i::__('Economia Criativa e da Cultura'),
            i::__('Economia, Produção e Áreas Técnicas da Cultura'),
            i::__('Ensaios'),
            i::__('Epístola'),
            i::__('Epopeia'),
            i::__('Escola de Samba'),
            i::__('Escultura (Artes Visuais)'),
            i::__('Escultura (Artesanato)'),
            i::__('Espetáculo de Circo'),
            i::__('Fábula'),
            i::__('Fandango'),
            i::__('Fanfarra'),
            i::__('Festa do Divino'),
            i::__('Festas Populares'),
            i::__('Festejos Juninos'),
            i::__('Ficção'),
            i::__('Filme-ensaio'),
            i::__('Filologia'),
            i::__('Carpintaria / Marcenaria'),
            i::__('Folia de Reis'),
            i::__('Fomento editorial'),
            i::__('Forró'),
            i::__('Forró (Dança)'),
            i::__('Transporte'),
            i::__('Frevo'),
            i::__('Frevo (dança)'),
            i::__('Funk'),
            i::__('Fuxico'),
            i::__('Navegação'),
            i::__('Geografia Humana'),
            i::__('Gestão criativa'),
            i::__('Comunicação Popular'),
            i::__('Grafite'),
            i::__('Gravura'),
            i::__('Guarânia'),
            i::__('Cultura Digital'),
            i::__('Humanidades'),
            i::__('Imóvel tombado'),
            i::__('Internet Podcasting'),
            i::__('Interseccionalidades'),
            i::__('Intervenção Urbana'),
            i::__('Jazz (Dança)'),
            i::__('Jogos Eletrônicos/Games'),
            i::__('Jongo'),
            i::__('Jornais e outros periódicos'),
            i::__('K-pop Dance'),
            i::__('Lambada'),
            i::__('Lapidação'),
            i::__('Sustentabilidade'),
            i::__('Lenda'),
            i::__('Letras e Literatura (Humanidades)'),
            i::__('Lidas Campeiras'),
            i::__('Linguística'),
            i::__('Turismo de Base Comunitária'),
            i::__('Literatura Infantil'),
            i::__('Comércio Local'),
            i::__('Livro, Leitura e Literatura'),
            i::__('Macramê'),
            i::__('Maracatu'),
            i::__('Maracatu (Dança)'),
            i::__('Marujada'),
            i::__('Mediação de Leitura'),
            i::__('Memórias'),
            i::__('Mídias Interativas'),
            i::__('Economia Solidária'),
            i::__('Mito'),
            i::__('Moda de Viola'),
            i::__('Mosaico'),
            i::__('Movimento Sound System'),
            i::__('Museologia'),
            i::__('Museu (Patrimônio Material)'),
            i::__('Museu tombado'),
            i::__('Reciclagem / Reaproveitamento'),
            i::__('Música de Câmara'),
            i::__('Música de Concerto'),
            i::__('Música Eletrônica'),
            i::__('Música Instrumental'),
            i::__('Música Popular'),
            i::__('Musical'),
            i::__('Novela'),
            i::__('Obra Seriada'),
            i::__('Oktober Fest'),
            i::__('Governança Territorial'),
            i::__('Orquestra Sinfônica'),
            i::__('Ourivesaria'),
            i::__('Outras Danças'),
            i::__('Outras Danças Clássicas'),
            i::__('Outras Danças Modernas'),
            i::__('Outras Danças Populares'),
            i::__('Paisagens Culturais'),
            i::__('Articulação Comunitária'),
            i::__('Participação Social'),
            i::__('Patrimônio Cultural Material'),
            i::__('Patrimônio Histórico Edificado'),
            i::__('Performance'),
            i::__('Performance Literária'),
            i::__('Permacultura'),
            i::__('Defesa de Direitos'),
            i::__('Pintura'),
            i::__('Poesia'),
            i::__('Políticas e Gestão Culturais'),
            i::__('Procissão do Fogaréu'),
            i::__('Produção Audiovisual'),
            i::__('Juventude'),
            i::__('Produção de Eventos'),
            i::__('Psicologia'),
            i::__('Punk'),
            i::__('Mulheres'),
            i::__('Rádio Comunitária'),
            i::__('Rádio e TV'),
            i::__('Rap'),
            i::__('Rasqueado'),
            i::__('Realidade Virtual'),
            i::__('Reggae'),
            i::__('Reisado'),
            i::__('Renda'),
            i::__('Renda de Bilro'),
            i::__('Repente'),
            i::__('Rima e improviso'),
            i::__('Rock'),
            i::__('Romance'),
            i::__('Romaria do Divino Pai Eterno'),
            i::__('Salsa (Dança)'),
            i::__('Salvaguarda do Patrimônio Cultural Imaterial'),
            i::__('Samba'),
            i::__('Samba (Dança)'),
            i::__('Samba de Roda'),
            i::__('Sapateado'),
            i::__('Sátira'),
            i::__('Sertanejo'),
            i::__('Sítio Arqueológico'),
            i::__('Sítios Históricos e Arqueológicos'),
            i::__('Slam'),
            i::__('Povos Originários'),
            i::__('Stand-up Comedy'),
            i::__('Street Jazz'),
            i::__('Tambor de Crioula'),
            i::__('Tango (Dança)'),
            i::__('Povos da Floresta'),
            i::__('Teatro de Bonecos'),
            i::__('Teatro de Improviso'),
            i::__('Teatro de Máscaras'),
            i::__('Teatro de Rua'),
            i::__('Teatro de Sombras'),
            i::__('Teatro do Absurdo'),
            i::__('Teatro do Oprimido'),
            i::__('Teatro Experimental'),
            i::__('Teatro Infantil'),
            i::__('Tecelagem'),
            i::__('Tecnobrega'),
            i::__('Visitante'),
            i::__('Teologia'),
            i::__('Tradução e Interpretação'),
            i::__('Tragédia'),
            i::__('Trançagem'),
            i::__('Transversalidades'),
            i::__('Vídeo'),
            i::__('Vídeo Experimental'),
            i::__('Vídeo Performance'),
            i::__('Vídeo por demanda'),
            i::__('Video Teatro'),
            i::__('Videoarte'),
            i::__('Videocast'),
            i::__('Videoclipe'),
            i::__('Videodança'),
            i::__('Webdesign'),
            i::__('Websérie'),
            i::__('Xaxado'),
            i::__('Xilogravura'),
            i::__('Outros'),
        )
    ),

    3 => array(
        'slug' => 'linguagem',
        'description' => i::__('Linguagem'),
        'required' => i::__("Você deve informar ao menos uma linguagem"),
        'entities' => array(
            'MapasCulturais\Entities\Event'
        ),

        'restricted_terms' => array(
            i::__('Soberania Digital Popular'),
            i::__('Soberania Alimentar'),
            i::__('Povos da Floresta'),
            i::__('Povos Originários'),
            i::__('Diversidade (LGBTQIAPN+)'),
            i::__('Feminista'),
            i::__('Infância'),
            i::__('Juventude'),
            i::__('Cultura'),
            i::__('Cultura Digital'),
            i::__('Inclusão Digital'),
            i::__('Acesso a Direitos'),
            i::__('Justiça Social'),
            i::__('Justiça Climática'),
            i::__('Governança Territorial'),
            i::__('Direitos da Terra'),
            i::__('Democracia'),
            i::__('Economia Solidária'),
            i::__('Educação Popular'),
            i::__('Agroecologia'),
            i::__('Comunicação Popular'),
            i::__('Audiovisual'),
            i::__('Cinema'),
            i::__('Fotografia'),
            i::__('Rádio Comunitária'),
            i::__('Podcast'),
            i::__('Artes Cênicas'),
            i::__('eatro'),
            i::__('Artes Circenses'),
            i::__('Música'),
            i::__('Dança'),
            i::__('Literatura'),
            i::__('Poesia Falada / Slam'),
            i::__('Design'),
            i::__('Artesanato'),
            i::__('Moda Sustentável'),
            i::__('Gastronomia Tradicional'),
            i::__('Saberes da Floresta'),
            i::__('Saberes Ancestrais'),
            i::__('Memória e Patrimônio'),
            i::__('Espiritualidade e Cura'),
            i::__('Tecnologia Social'),
            i::__('Ciência Cidadã'),
            i::__('Inovação Comunitária'),
            i::__('Territórios Livres'),
            i::__('Movimentos Sociais'),
            i::__('Outros')
        ),
    ),

   
    4 => array(
        'slug' => 'funcao',
        'description' => i::__('Função'),
        'entities' => array(
            'MapasCulturais\Entities\Agent'
        ),
        'restricted_terms' => array(
           i::__('Agente Ambiental'),
           i::__('Agente Comunitário(a)'),
           i::__('Agente Cultural'),
           i::__('Agente de Saúde'),
           i::__('Agente Pastoral'),
           i::__('Agricultor(a)'),
           i::__('Agroextrativista'),
           i::__('Analista de Dados'),
           i::__('Apicultor(a)'),
           i::__('Apresentador(a)'),
           i::__('Apoiador(a)'),
           i::__('Apoiador(a) Técnico(a)'),
           i::__('Artesão(ã)'),
           i::__('Articulador(a)'),
           i::__('Articulador(a) de Rede'),
           i::__('Artista'),
           i::__('Ator / Atriz'),
           i::__('Benzedeira'),
           i::__('Barqueiro(a)'),
           i::__('Brigadista'),
           i::__('Caçador(a)'),
           i::__('Cantor(a)'),
           i::__('Carpinteiro(a)'),
           i::__('Catequista'),
           i::__('Ceramista'),
           i::__('Circense'),
           i::__('Comerciante'),
           i::__('Compositor(a)'),
           i::__('Comunicador(a) Popular'),
           i::__('Condutor(a) de Turistas'),
           i::__('Construtor(a) de Embarcações'),
           i::__('Coordenador(a)'),
           i::__('Cozinheira Comunitária'),
           i::__('Cozinheiro(a)'),
           i::__('Cuidador(a)'),
           i::__('Cuidador(a) de Idosos'),
           i::__('Curandeiro(a)'),
           i::__('Dançarino(a)'),
           i::__('Defesa de Direitos'),
           i::__('Desenvolvedor(a)'),
           i::__('Designer'),
           i::__('DJ'),
           i::__('Educador(a)'),
           i::__('Educador(a) Infantil'),
           i::__('Editor(a) de Vídeo'),
           i::__('Enfermeiro(a)'),
           i::__('Erveiro(a)'),
           i::__('Escritor(a)'),
           i::__('Esportista'),
           i::__('Estudante'),
           i::__('Facilitador(a)'),
           i::__('Facilitador(a) Territorial'),
           i::__('Feirante'),
           i::__('Fotógrafo(a)'),
           i::__('Fotógrafo(a) Comunitário(a)'),
           i::__('Gestor(a) Ambiental'),
           i::__('Gestor(a) de Projeto'),
           i::__('Guia Comunitário(a)'),
           i::__('Guia de Trilha'),
           i::__('Guia Espiritual'),
           i::__('Ilustrador(a)'),
           i::__('Instrutor(a) de Esporte'),
           i::__('Jornalista'),
           i::__('Juventude Comunitária'),
           i::__('Liderança Comunitária'),
           i::__('Liderança Religiosa'),
           i::__('Marceneiro(a)'),
           i::__('Mediador(a)'),
           i::__('Missionário(a)'),
           i::__('Mobilizador(a)'),
           i::__('Motorista'),
           i::__('Mestre de Obras'),
           i::__('Mulher de Rede'),
           i::__('Músico(a)'),
           i::__('Operador(a) de Rádio'),
           i::__('Outros'),
           i::__('Pajé'),
           i::__('Palhaço(a)'),
           i::__('Parteira'),
           i::__('Parteira Espiritual'),
           i::__('Parteira Tradicional'),
           i::__('Pedreiro(a)'),
           i::__('Pesquisador(a)'),
           i::__('Pescador(a)'),
           i::__('Poeta / Slamer'),
           i::__('Presidente de Associação'),
           i::__('Produtor(a) Audiovisual'),
           i::__('Produtor(a) Cultural'),
           i::__('Produtor(a) Rural'),
           i::__('Programador(a)'),
           i::__('Radialista'),
           i::__('Raizeiro(a)'),
           i::__('Representante de Associação'),
           i::__('Rezador(a)'),
           i::__('Roteirista'),
           i::__('Secretário(a)'),
           i::__('Seringueiro(a)'),
           i::__('Tecelão(ã)'),
           i::__('Técnico(a) Ambiental'),
           i::__('Técnico(a) de Enfermagem'),
           i::__('Técnico(a) de Informática'),
           i::__('Tesoureiro(a)'),
           i::__('Trabalhador(a) Doméstico(a)'),
           i::__('Treinador(a)'),
           i::__('Trançador(a)'),
           i::__('Voluntário(a)'),
           i::__('Visitante'),
           i::__('Xamã'),
        )
    )
);
